### ISSUE TITLE
chatbot quality check not working if there is no WFR node

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/idems_translation#21]
the fix_translated_arguments function and create_connection_matrix function in it break if there is a send_msg node with quick replies with no wait_for_response node associated to it

(@edmoss345 this is not urgent to fix, just something I just noticed and wanted to keep track of)

**Comment by fagiothree** [comment]
Hey @edmoss345 sorry for never replying to this. Would you have some time to work on it next week?
Thanks a lot!

**Comment by edmoss345** [comment]
Hi @fagiothree sorry this completely slipped my mind! Yes I should have some time next week to look into this further

**Comment by fagiothree** [comment]
no worries, I had also completely forgotten about this. If would be great if you could find some time, thank you! Let me know if you need any clarification.
