### ISSUE TITLE
In code for adding quicke replies to msg text the regex is not working for non latin alphabets (?)

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/idems_translation#35]
https://github.com/IDEMSInternational/idems_translation/blob/fb3f024082234b91b7971823fa670aed03374b42/chatbot/insert/add_quick_replies_to_msg_text_and_localization.js#L151

I think that the regex used here (and below for other test cases) for matching quick replies and arguments does not work for non Latin alphabets? I am trying to use the code on flows translated in Thai. The case "has_only_phrase" is working fine because we are matching strings using ==

**Comment by istride** [comment]
Looks like we will have to use [unicode regular expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#using_unicode_regular_expressions). I strongly recommend making sure that there is adequate automatic testing in place before making changes - ideally, unit tests, but anything is better than nothing. Once tests are in place, this may be a good opportunity to refactor a bit, if time allows.

I'm going to leave this with @edmoss345, but I'm happy to assist.

**Comment by edmoss345** [comment]
Thanks @istride, agreed probably best to have some more tests in place before making significant changes. Will look into this tomorrow then we can maybe discuss in our meeting on Wednesday

**Comment by edmoss345** [comment]
@fagiothree could you share the example file with the Thai in it so I can make some tests specific to this issue
