### ISSUE TITLE
merge_files_post_translation.py improvement

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/idems_translation#65]
Currently, `merge_files_post_translation.py` seems to rely on both `PostTranslation` and `PostTranslationJSONs`, the latter being typically set to `app/4_result_from_translators`. Regularly there are files hanging around in this folder from previous times this script was run, and this causes dictionaries to be generated in _all_ languages corresponding to files in this folder, rather than just the languages that relevant, which can be taken from `PostTranslation`. 

[screen-capture (88).webm](https://github.com/IDEMSInternational/idems_translation/assets/74557272/dce7eba7-c064-4fee-a636-cb7aa80e9a5d)

(my/ms = malaysia/malay, mx/es = mexico/spanish)

N.B. this is not urgent.

**Comment by edmoss345** [comment]
Thanks for the info Esmee, I will investigate and get back to you

**Comment by esmeetewinkel** [comment]
@edmoss345 Any chance you can look into this? 

Basically all that is needed is to add a line at the start of the `merge_files_post_translation` script to empty the local folder `4_result_from_translators` if it is not empty. Currently the files in this folder are gitignored, but not deleted, which creates the issue. 

If you don't have time for this chatgpt and I can give it a try - but I'm guessing this might just take a few minutes for you.
